# Generated by Django 4.1.2 on 2022-10-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatuser_alter_conversationuser_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationuser',
            old_name='user',
            new_name='chat_user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='chat_user',
        ),
    ]
