# Generated by Django 4.1.2 on 2022-10-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_user_conversationuser_chat_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConversationUser',
            new_name='ConversationChatUser',
        ),
    ]
